In [1]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


2024-11-19 14:22:49.359 python[1596:24331] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-19 14:22:49.359 python[1596:24331] +[IMKInputSession subclass]: chose IMKInputSession_Modern


True

In [2]:
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt'); nltk.download('punkt_tab')

tokens = word_tokenize("Hello World, This is a dog.")

words = [word for word in tokens if word.isalpha()]
print (words)

['Hello', 'World', 'This', 'is', 'a', 'dog']


[nltk_data] Downloading package punkt to /Users/tommyhong/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/tommyhong/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [3]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

from nltk.corpus import stopwords
print(stopwords.words('english')[:20])

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


[nltk_data] Downloading package punkt to /Users/tommyhong/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/tommyhong/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [4]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
text = "This is a dog."
print(word_tokenize(text))

['This', 'is', 'a', 'dog', '.']


[nltk_data] Downloading package punkt to /Users/tommyhong/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [5]:
from nltk.tokenize import sent_tokenize
text = "This is a house. This is a dog."
print(sent_tokenize(text))

['This is a house.', 'This is a dog.']


In [8]:
from tensorflow.keras.preprocessing.text import *

print(text_to_word_sequence("This is a dog."))

['this', 'is', 'a', 'dog']


In [9]:
import numpy as np
from tensorflow.keras.utils import to_categorical

text = ["cat", "dog", "cat", "bird"]

total_pets = ["cat", "dog", "turtle", "fish", "bird"]
print("text=", text)

text= ['cat', 'dog', 'cat', 'bird']


In [10]:
mapping = {}
for x in range(len(total_pets)):
    mapping[total_pets[x]] = x #“cat"->0, "dog"->1, ...
print(mapping)
# 단어들을 순차적인 정수 인덱스로 만든다.
for x in range(len(text)):
    text[x] = mapping[text[x]]
print("text=", text)
# 순차적인 정수 인덱스를 원-핫 인코딩으로 만든다.
one_hot_encode = to_categorical(text)
print("text=", one_hot_encode)

{'cat': 0, 'dog': 1, 'turtle': 2, 'fish': 3, 'bird': 4}
text= [0, 1, 0, 4]
text= [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
t = Tokenizer()

text = """Deep learning is part of a broader family of machine learning methods
based on artificial neural networks with representation learning."""
t.fit_on_texts([text])

print("단어집합 : ", t.word_index)

단어집합 :  {'learning': 1, 'of': 2, 'deep': 3, 'is': 4, 'part': 5, 'a': 6, 'broader': 7, 'family': 8, 'machine': 9, 'methods': 10, 'based': 11, 'on': 12, 'artificial': 13, 'neural': 14, 'networks': 15, 'with': 16, 'representation': 17}


In [2]:
seq = t.texts_to_sequences([text])[0]
print(text,"->", seq)

Deep learning is part of a broader family of machine learning methods
based on artificial neural networks with representation learning. -> [3, 1, 4, 5, 2, 6, 7, 8, 2, 9, 1, 10, 11, 12, 13, 14, 15, 16, 17, 1]


In [3]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X = pad_sequences([[7, 8, 9], [1, 2, 3, 4, 5], [7]], maxlen=3, padding='pre')
print(X)

[[7 8 9]
 [3 4 5]
 [0 0 7]]


In [4]:
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

# 입력 형태: (batch_size, input_length)=(32, 3)
# 출력 형태: (None, 3, 4)

model = Sequential()
model.add(Embedding(100, 4, input_length=3))
input_array = np.random.randint(100, size=(32, 3))
model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)
print(output_array.shape)

1/1 [==============================] - 0s 58ms/step
(32, 3, 4)


In [5]:
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

docs = [  'additional income',
          'best price',
          'big bucks',
          'cash bonus',
          'earn extra cash',
          'spring savings certificate',
          'valero gas marketing',
          'all domestic employees',
          'nominations for oct',
          'confirmation from spinner']

labels = np.array([1,1,1,1,1,0,0,0,0,0])
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[20, 15], [15, 33], [4, 21], [14, 11], [8, 21, 14], [18, 22, 44], [37, 41, 41], [44, 35, 30], [37, 16, 2], [22, 48, 41]]


In [6]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[20 15  0  0]
 [15 33  0  0]
 [ 4 21  0  0]
 [14 11  0  0]
 [ 8 21 14  0]
 [18 22 44  0]
 [37 41 41  0]
 [44 35 30  0]
 [37 16  2  0]
 [22 48 41  0]]


In [7]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_docs, labels, epochs=50, verbose=0)
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy=', accuracy)

Accuracy= 1.0


In [9]:
test_doc = ['big income']
encoded_docs = [one_hot(d, vocab_size) for d in test_doc]
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(model.predict(padded_docs))

1/1 [==============================] - 0s 32ms/step
[[0.57640487]]


In [18]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM
from tensorflow.keras.preprocessing.text import Tokenizer

# Sample text data
text_data = """Soft as the voice of an angel
Breathing a lesson unhead
Hope with a gentle persuasion
Whispers her comforting word
Wait till the darkness is over
Wait till the tempest is done
Hope for sunshine tomorrow
After the shower
"""


In [19]:
# Tokenize and encode the text
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text_data])
encoded = tokenizer.texts_to_sequences([text_data])[0]
vocab_size = len(tokenizer.word_index) + 1
print('Vocabulary size:', vocab_size)

Vocabulary size: 32


In [20]:
print(tokenizer.word_index)
vocab_size = len(tokenizer.word_index) + 1
print('Vocabulary Size : %d' % vocab_size)

{'the': 1, 'a': 2, 'hope': 3, 'wait': 4, 'till': 5, 'is': 6, 'soft': 7, 'as': 8, 'voice': 9, 'of': 10, 'an': 11, 'angel': 12, 'breathing': 13, 'lesson': 14, 'unhead': 15, 'with': 16, 'gentle': 17, 'persuasion': 18, 'whispers': 19, 'her': 20, 'comforting': 21, 'word': 22, 'darkness': 23, 'over': 24, 'tempest': 25, 'done': 26, 'for': 27, 'sunshine': 28, 'tomorrow': 29, 'after': 30, 'shower': 31}
Vocabulary Size : 32


In [21]:
sequences = list()
for i in range(1, len(encoded)):
    sequence = encoded[i-1:i+1]
sequences.append(sequence)
print(sequences)
print('Total Sequences : %d' % len(sequences))

[[1, 31]]
Total Sequences : 1


In [22]:
sequences = np.array(sequences)
X, y = sequences[:,0],sequences[:,1]
print("X=", X)
print("y=", y)
X = X.reshape((X.shape[0], 1)) # (samples, timesteps)

X= [1]
y= [31]


In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN, LSTM
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=1))
model.add(LSTM(50))
model.add(Dense(vocab_size, activation='softmax'))

In [24]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=500, verbose=2)

Epoch 1/500
1/1 - 1s - loss: 3.4630 - accuracy: 0.0000e+00 - 767ms/epoch - 767ms/step
Epoch 2/500
1/1 - 0s - loss: 3.4587 - accuracy: 0.0000e+00 - 2ms/epoch - 2ms/step
Epoch 3/500
1/1 - 0s - loss: 3.4543 - accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 4/500
1/1 - 0s - loss: 3.4498 - accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 5/500
1/1 - 0s - loss: 3.4454 - accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 6/500
1/1 - 0s - loss: 3.4408 - accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 7/500
1/1 - 0s - loss: 3.4363 - accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 8/500
1/1 - 0s - loss: 3.4316 - accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 9/500
1/1 - 0s - loss: 3.4269 - accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 10/500
1/1 - 0s - loss: 3.4221 - accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 11/500
1/1 - 0s - loss: 3.4171 - accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 12/500
1/1 - 0s - loss: 3.4121 - accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 13/500
1/1 - 0s - loss: 3.4070 - accuracy: 

In [25]:
test_text = 'Wait'
encoded = tokenizer.texts_to_sequences([test_text])[0]
encoded = np.array(encoded)

onehot_output = model.predict(encoded)
print('onehot_output=', onehot_output)

output = np.argmax(onehot_output)
print('output=', output)

print(test_text, "=>", end=" ")
for word, index in tokenizer.word_index.items():
    if index == output:
        print(word)

1/1 [==============================] - 0s 148ms/step
onehot_output= [[0.02724354 0.02852597 0.02676919 0.02818197 0.02710003 0.027107
  0.02675476 0.02835245 0.02767495 0.02704785 0.02740993 0.02775357
  0.02837306 0.02663882 0.02901122 0.02792208 0.02748626 0.02676671
  0.02719379 0.02717571 0.02918015 0.02846962 0.02746332 0.02929452
  0.02759856 0.0279234  0.02912562 0.0287298  0.02698818 0.02749237
  0.02742933 0.13981633]]
output= 31
Wait => shower


In [26]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt

imdb = keras.datasets.imdb
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)
print(x_train[0])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


In [27]:
# Word to Integer Index Dictionary
word_to_index = imdb.get_word_index()

# Few index in front are using specific methods
word_to_index = {k:(v+3) for k,v in word_to_index.items()}
word_to_index["<PAD>"] = 0 # 문장을 채우는 기호
word_to_index["<START>"] = 1 # 시작을 표시
word_to_index["<UNK>"] = 2 # 알려지지 않은 토큰
word_to_index["<UNUSED>"] = 3

index_to_word = dict([(value, key) for (key, value) in word_to_index.items()])
print(' '.join([index_to_word[index] for index in x_train[0]]))

1641221/1641221 [==============================] - 1s 0us/step
<START> this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert <UNK> is an amazing actor and now the same being director <UNK> father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for <UNK> and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also <UNK> to the two little boy's that played the <UNK> of norman and paul they were just brilliant children are often left out of the <UNK> list i think because the stars that play them all grown up are such a big profile for the whole fi

In [28]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
x_train = pad_sequences(x_train, maxlen=100)
x_test = pad_sequences(x_test, maxlen=100)
vocab_size = 10000
model = Sequential()
model.add(Embedding(vocab_size, 64,
                    input_length=100))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 100, 64)           640000    
                                                                 
 flatten_1 (Flatten)         (None, 6400)              0         
                                                                 
 dense_3 (Dense)             (None, 64)                409664    
                                                                 
 dropout (Dropout)           (None, 64)                0         
                                                                 
 dense_4 (Dense)             (None, 1)                 65        
                                                                 
Total params: 1049729 (4.00 MB)
Trainable params: 1049729 (4.00 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [29]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=64, epochs=20, verbose=1,
                    validation_data=(x_test, y_test))

Epoch 1/20
391/391 [==============================] - 2s 6ms/step - loss: 0.4613 - accuracy: 0.7653 - val_loss: 0.3365 - val_accuracy: 0.8509
Epoch 2/20
391/391 [==============================] - 2s 6ms/step - loss: 0.1664 - accuracy: 0.9396 - val_loss: 0.4013 - val_accuracy: 0.8340
Epoch 3/20
391/391 [==============================] - 2s 6ms/step - loss: 0.0271 - accuracy: 0.9940 - val_loss: 0.5280 - val_accuracy: 0.8322
Epoch 4/20
391/391 [==============================] - 2s 6ms/step - loss: 0.0046 - accuracy: 0.9998 - val_loss: 0.5965 - val_accuracy: 0.8382
Epoch 5/20
391/391 [==============================] - 3s 7ms/step - loss: 0.0017 - accuracy: 0.9999 - val_loss: 0.6379 - val_accuracy: 0.8391
Epoch 6/20
391/391 [==============================] - 3s 7ms/step - loss: 8.1020e-04 - accuracy: 1.0000 - val_loss: 0.6766 - val_accuracy: 0.8395
Epoch 7/20
391/391 [==============================] - 3s 7ms/step - loss: 4.9143e-04 - accuracy: 1.0000 - val_loss: 0.7095 - val_accuracy: 0.840

In [30]:
results = model.evaluate(x_test, y_test, verbose=2)
print(results)

782/782 - 1s - loss: 1.0372 - accuracy: 0.8406 - 595ms/epoch - 760us/step
[1.0371841192245483, 0.8405600190162659]


In [31]:
review = "What can I say about this movie that was already said? It is my favorite time travel sci-fi, adventure epic comedy in the 80's and I love this movie to death! When I saw this movie I was thrown out by its theme. An excellent sci-fi, adventure epic, I LOVE the 80s. It's simple the greatest time travel movie ever happened in the history of world cinema. I love this movie to death, I love, LOVE, love it!"

In [34]:
import re
review = re.sub("[^0-9a-zA-Z ]", "", review).lower()
review_encoding = []

#Etorate each vocabulary in sentence
for w in review.split():
    index = word_to_index.get(w, 2) # Return 2 if there isn't exist in dictionary
    if index <= 10000: # under 10000 vocabularies
        review_encoding.append(index)
    else:
        review_encoding.append(word_to_index["UNK"])

# handout to 2 - Dimension list
test_input = pad_sequences([review_encoding], maxlen = 100)
value = model.predict(test_input) # Prediction
if(value > 0.5):
    print("Positive Review.")
else:
    print("Negative Review.") 

1/1 [==============================] - 0s 24ms/step
Positive Review.
